class Bubble_HERPUsable : Bubble_DERPUsable
{
    override bool CheckVisible(Actor target) {
        return super.CheckVisible(target) && !(target.player.cmd.buttons & BT_ZOOM);
    }
    
    default
    {
        Bubble_Weapon.weaponClass "HERPUsable";
        HideousBubble.lower 12.;
    }

    states
    {
        Spawn:
            HERP A 1
            {
                angle = target.angle;
                translation = target.translation;
            }
            Wait;
    }
}
